apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: scaffolder-backend-module-github-team
  title: GitHub Team Scaffolder Module
  description: A Backstage scaffolder backend module for creating GitHub teams with comprehensive member management
  annotations:
    github.com/project-slug: backstage/community-plugins
    backstage.io/source-location: url:https://github.com/backstage/community-plugins/tree/main/workspaces/scaffolder-backend-module-github-team
spec:
  type: plugin
  lifecycle: production
  owner: community
  system: backstage
  subcomponentOf: scaffolder-backend